language: c
compiler: gcc
script:
 - make CFLAGS=-coverage
 - make visualizer CFLAGS=-coverage
 - ./cubically fu examples/cat.cb < examples/input.txt
 - ./cubically fu examples/cubifier.cb < examples/input.txt
 - ./cubically fu examples/sum.cb < examples/input-integer.txt
 - gcov src/*.c

after_success: 
 - bash <(curl -s https://codecov.io/bash)
