language: c
compiler: gcc
script:
 - make CFLAGS=-coverage
 - make visualizer CFLAGS=-coverage
 - ./cubically fu examples/cat.cb < examples/input.txt
 - ./cubically fu examples/cubifier.cb < examples/input.txt
 - ./cubically fu examples/sum.cb < examples/input-integer.txt
 - ./cubically fu examples/eval.cb <<<R2L2U2D2F2B2
 - ./cubically fu examples/huge.cb
 - ./cubically fu examples/period.cb <<<RLUD
 - ./cubically fs R2?{haha\ nope}
 - ./cubically fs 'RLUDFBMESXYZ^<>_2|/=2:'
 - ./cubically ThisWontWork || echo 'This is so the build succeeds'
 - ./cubically fu ThisWontWork || echo 'This is so the build succeeds'
 - ./cubically us R2L2U2D2F2B\' 6
 - ./cubically us R2L2U2D2F2B2 0
 - ./cubically us R2L2U2D2F2B2 -3
 - ./cubically fcd examples/cat.cb < examples/input.txt
 - ./cubically fu examples/subscripts.cb 15
 - ./cubically fu examples/superscripts.cb 15
 - ./cubically fu examples/depth.cb
 - ./cubically fu examples/functions.cb
 - ./cubically fSup examples/solve.cb
 - ./cubically us '(0R)'
 - gcov src/*.c

after_success:
 - bash <(curl -s https://codecov.io/bash)
