language: c
compiler: gcc
script:
 - make CFLAGS=-coverage
 - make visualizer CFLAGS=-coverage
 - ./cubically fu examples/cat.cb < examples/input.txt
 - ./cubically fu examples/cubifier.cb < examples/input.txt
 - ./cubically fu examples/sum.cb < examples/input-integer.txt
 - ./cubically fu examples/eval.cb < examples/input.txt
 - ./cubically fs 'RLUDFBMESXYZ^<>_2|'
 - ./cubically ThisWontWork || echo 'This is so the build succeeds'
 - ./cubically fs R2L2U2D2F2B2 6
 - ./cubically fs R2L2U2D2F2B2 0
 - ./cubically fs R2L2U2D2F2B2 -3
 - ./cubically fud examples/cubifier.cb < examples/input.txt
 - gcov src/*.c

after_success:
 - bash <(curl -s https://codecov.io/bash)
